import '../../assets/css/Policy/policy.css'
import logo from '../../assets/images/jupit_white.svg'
import Phone from '../../assets/images/phone1.png'
import banner from '../../assets/images/banner.svg'
import umbrella from '../../assets/images/umbrella.svg'
import { Link } from 'react-router-dom'
import { Link as ScrollLink } from 'react-scroll'
import { useEffect, useState } from 'react'
const Index = ()=>{
   
    return (
        <div className="policy">
             <div className='privacyText'>
                    <div className='policyText'>
                        <div className='policyText-Title'>Introduction</div>
                        <div className='policyText-content'>
                            <p>As a company, we understand the importance of preventing money laundering and terrorist financing and adhere to carrying on business in accordance with the highest standards of anti-money laundering and terrorist financing in Nigeria.</p>
                            <p>Jupit Technologies, as a FinTech company, is subject to the regulatory framework designed to prevent money laundering in Nigeria. This framework includes such laws as: Terrorism Prevention Act 2103, Money Laundering Prohibition Act 2011 (as amended) and others. To meet this commitment, Jupit Technologies has put in place some policies and procedures. This document sets forth the company's expectations for its users, employees, and other business partners.</p>
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Our Policy Statement on AML and CTF</div>
                        <div className='policyText-content'>
                            <p>It is Jupit's policy to comply with all Anti-Money Laundering and Combating Terrorist Financing Laws applicable to our operations in Nigeria. To this end, Jupit Technologies will only conduct business with users and partners who are involved in legitimate business activity and whose funds are derived from legitimate sources.</p>
                            <p>This Policy is intended to prevent money laundering, including the need to have adequate systems and controls in place to mitigate the risk of the firm being used to facilitate financial crime and to help our users and employees to understand where breaches of AML Laws might arise and to support them in making the right decisions in line with our corporate position as stated in this Policy.</p>
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Who is subject to this Policy?</div>
                        <div className='policyText-content'>
                            <p>This Policy applies to all Jupit's operations, including all legal entities owned or controlled by Jupit, and to all directors, employees, users, and other third parties acting on behalf of the foregoing.</p>
                        </div>

                    </div>

                    

                    {/* <div className='policyText'>
                        <div className='policyText-Title'>Custodian</div>
                        <div className='policyText-content'>
                            <p>Jupit Technologies is the custodian and is responsible for protecting the privacy of all personal data that is shared and/or collected through access to https://jupitapp.co.</p>
                            <p>If you have any questions about this Privacy Policy or our privacy practices, please contact us below –<br/><br/>
                                Customer Service Desk<br/>
                                Email address: hello@jupitapp.co

                            </p>
                        </div>

                    </div> */}

                    <div className='policyText'>
                        <div className='policyText-Title'>What do we mean by Money Laundering and Terrorist Financing ?</div>
                        <div className='policyText-content'>
                            <p>Money laundering is the processing of criminal proceeds to disguise their illegal origin. This process involves cleaning money generated by criminal activity, such as drug trafficking, terrorist funding or cyber-fraud, to appear to have come from a legitimate source.</p>
                            <p>Terrorism Financing is defined as providing, depositing, distributing or collection funds, directly or indirectly, intended to be used, or knowing that these funds are to be wholly or partially use, for the committing of terrorist acts.</p>
                            <p>The following types of activities are considered to be “money laundering” and are prohibited under this Policy:</p>
                            <p className='paragraph'>
                               
                                <p>
                                   (a) the transfer of funds to a Jupit account knowing or suspecting that such funds is derived from criminal or certain specified unlawful activity, for the purpose of disguising the illicit origin of the funds;
                                </p>
                                
                            </p>
                            <p className='paragraph'>
                              
                                <p>
                                (b) conducting any type of exchange transaction which involves criminally acquired funds;
                                </p>
                                
                            </p>
                            <p className='paragraph'>
                                
                                <p>
                                   (c) the concealment or disguise of the true nature, source, disposition, transfer, rights with respect to ownership or control of criminal funds;
                                </p>
                               
                            </p>
                            <p className='paragraph'>
                               
                                <p>
                                (d) promoting the carrying on of unlawful activity; and
                                </p>
                                
                            </p>
                            
                            <p className='paragraph'>
                               
                                <p>
                                (e) participation in, association to commit, attempts to commit and aiding, abetting, facilitating and counselling the commission of any of the actions mentioned in the foregoing points.
                                </p>
                               
                            </p>
                            
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>What do we mean by Money Laundering and Terrorist Financing?</div>
                        <div className='policyText-content'>
                            <p>
                                Money laundering is the processing of criminal proceeds to disguise their illegal origin. This process involves cleaning money generated by criminal activity, such as drug trafficking, terrorist funding or cyber-fraud, to appear to have come from a legitimate source.
                            </p>
                            <p>Terrorism Financing is defined as providing, depositing, distributing or collection funds, directly or indirectly, intended to be used, or knowing that these funds are to be wholly or partially use, for the committing of terrorist acts.</p>
                            <p>The following types of activities are considered to be “money laundering” and are prohibited under this Policy:</p>
                            <p className='paragraph'>
                              
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>a.</p>
                                        <p className='divalphabelt'>
                                            the transfer of funds to a Jupit account knowing or suspecting that such funds is derived from criminal or certain specified unlawful activity, for the purpose of disguising the illicit origin of the funds.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>b.</p>
                                        <p className='divalphabelt'>
                                            conducting any type of exchange transaction which involves criminally acquired funds;
                                        </p>	
                                </p>

                                <p className='specialParagraph'>
                                    <p className='alphabelt'>c.</p>
                                        <p className='divalphabelt'>
                                            the concealment or disguise of the true nature, source, disposition, transfer, rights with respect to ownership or control of criminal funds;
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>d.</p>
                                        <p className='divalphabelt'>
                                            promoting the carrying on of unlawful activity; and
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>e.</p>
                                        <p className='divalphabelt'>
                                            participation in, association to commit, attempts to commit and aiding, abetting, facilitating and counselling the commission of any of the actions mentioned in the foregoing points.
                                        </p>	
                                </p>
  
                            </p>
                        
                        </div>

                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>Red Flag</div>
                        <div className='policyText-content'>
                            <p>Where any suspicions arise that criminal conduct may have taken place involving a user, employee or third party, you should consider whether there is a risk that money laundering or terrorist financing has occurred or may occur.</p>
                            <p>Some examples of red flags to be reported include:</p>
                            <p className='paragraph'>
                              
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>a.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Public identity check specialist/organizations</span> - In request to distinguish and forestall deceitful transaction and conform to pertinent regulations and administrative prerequisites, we might impart your information to third party identity confirmation specialist/organizations who will verify your identity/personality against accessible openly available reports and other public database.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>b.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Banks and other monetary institution</span> - In request to handle payments and settlements and follow appropriate regulations and administrative necessities we might impart your information to banks and monetary establishments.
                                        </p>	
                                </p>

                                <p className='specialParagraph'>
                                    <p className='alphabelt'>c.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Service providers</span> - We might impart your information to service source that we connect with their administrations to execute different business capacities. Instances of these service instructions incorporate: cloud depository, network infrastructure, product campaigns, data analytics and so forth.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>d.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Proficient consultants</span> - We might impart your information to proficient consultants to avail ourselves with specialized, monetary or lawful counseling administrations or in consistence with our lawful commitments.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>e.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Organizations or other establishments during corporate redesigns</span> - If an adjustment of our corporate design happens because of the deal, move or consolidation of parts of our business or our resources or that of another establishment by us, then, at that point, the new corporate substance might involve your own information similarly as set out in this protection strategy. You will get earlier notification of any adjustment of appropriate approaches.
                                        </p>	
                                </p>

                                <p className='specialParagraph'>
                                    <p className='alphabelt'>f.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Law Enforcement/Regulatory proxy and authorities</span> - We might impart your information to regulation authorization proxy and authorities assuming we are limited by regulation or any legitimate technique to share same or when we trust sincerely that the exposure of your data is important to forestall actual damage or monetary misfortune, to report presumed criminal behavior, or to research infringement of our Terms of Services or some other relevant arrangements.
                                        </p>	
                                </p>




                                
                            </p>
                            
                        </div>

                    </div>
             </div>
          
        </div>
    )
}
export default Index;