import '../../assets/css/Policy/policy.css'
import logo from '../../assets/images/jupit_white.svg'
import Phone from '../../assets/images/phone1.png'
import banner from '../../assets/images/banner.svg'
import umbrella from '../../assets/images/umbrella.svg'
import { Link } from 'react-router-dom'
import { Link as ScrollLink } from 'react-scroll'
import { useEffect, useState } from 'react'
const Index = ()=>{
   
    return (
        <div className="policy">
             <div className='privacyText'>
                    <div className='policyText'>
                        <div className='policyText-Title'>Introduction</div>
                        <div className='policyText-content'>
                            <p>As a company, we understand the importance of preventing money laundering and terrorist financing and adhere to carrying on business in accordance with the highest standards of anti-money laundering and terrorist financing in Nigeria.</p>
                            <p>Jupit Technologies, as a FinTech company, is subject to the regulatory framework designed to prevent money laundering in Nigeria. This framework includes such laws as: Terrorism Prevention Act 2103, Money Laundering Prohibition Act 2011 (as amended) and others. To meet this commitment, Jupit Technologies has put in place some policies and procedures. This document sets forth the company's expectations for its users, employees, and other business partners.</p>
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Our Policy Statement on AML and CTF</div>
                        <div className='policyText-content'>
                            <p>It is Jupit's policy to comply with all Anti-Money Laundering and Combating Terrorist Financing Laws applicable to our operations in Nigeria. To this end, Jupit Technologies will only conduct business with users and partners who are involved in legitimate business activity and whose funds are derived from legitimate sources.</p>
                            <p>This Policy is intended to prevent money laundering, including the need to have adequate systems and controls in place to mitigate the risk of the firm being used to facilitate financial crime and to help our users and employees to understand where breaches of AML Laws might arise and to support them in making the right decisions in line with our corporate position as stated in this Policy.</p>
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Who is subject to this Policy?</div>
                        <div className='policyText-content'>
                            <p>This Policy applies to all Jupit's operations, including all legal entities owned or controlled by Jupit, and to all directors, employees, users, and other third parties acting on behalf of the foregoing.</p>
                        </div>

                    </div>

                    

                    {/* <div className='policyText'>
                        <div className='policyText-Title'>Custodian</div>
                        <div className='policyText-content'>
                            <p>Jupit Technologies is the custodian and is responsible for protecting the privacy of all personal data that is shared and/or collected through access to https://jupitapp.co.</p>
                            <p>If you have any questions about this Privacy Policy or our privacy practices, please contact us below –<br/><br/>
                                Customer Service Desk<br/>
                                Email address: hello@jupitapp.co

                            </p>
                        </div>

                    </div> */}

                    <div className='policyText'>
                        <div className='policyText-Title'>What do we mean by Money Laundering and Terrorist Financing ?</div>
                        <div className='policyText-content'>
                            <p>Money laundering is the processing of criminal proceeds to disguise their illegal origin. This process involves cleaning money generated by criminal activity, such as drug trafficking, terrorist funding or cyber-fraud, to appear to have come from a legitimate source.</p>
                            <p>Terrorism Financing is defined as providing, depositing, distributing or collection funds, directly or indirectly, intended to be used, or knowing that these funds are to be wholly or partially use, for the committing of terrorist acts.</p>
                            <p>The following types of activities are considered to be “money laundering” and are prohibited under this Policy:</p>
                            <p className='paragraph'>
                               
                                <p>
                                   (a) the transfer of funds to a Jupit account knowing or suspecting that such funds is derived from criminal or certain specified unlawful activity, for the purpose of disguising the illicit origin of the funds;
                                </p>
                                
                            </p>
                            <p className='paragraph'>
                              
                                <p>
                                (b) conducting any type of exchange transaction which involves criminally acquired funds;
                                </p>
                                
                            </p>
                            <p className='paragraph'>
                                
                                <p>
                                   (c) the concealment or disguise of the true nature, source, disposition, transfer, rights with respect to ownership or control of criminal funds;
                                </p>
                               
                            </p>
                            <p className='paragraph'>
                               
                                <p>
                                (d) promoting the carrying on of unlawful activity; and
                                </p>
                                
                            </p>
                            
                            <p className='paragraph'>
                               
                                <p>
                                (e) participation in, association to commit, attempts to commit and aiding, abetting, facilitating and counselling the commission of any of the actions mentioned in the foregoing points.
                                </p>
                               
                            </p>
                            
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>What do we mean by Money Laundering and Terrorist Financing?</div>
                        <div className='policyText-content'>
                            <p>
                                Money laundering is the processing of criminal proceeds to disguise their illegal origin. This process involves cleaning money generated by criminal activity, such as drug trafficking, terrorist funding or cyber-fraud, to appear to have come from a legitimate source.
                            </p>
                            <p>Terrorism Financing is defined as providing, depositing, distributing or collection funds, directly or indirectly, intended to be used, or knowing that these funds are to be wholly or partially use, for the committing of terrorist acts.</p>
                            <p>The following types of activities are considered to be “money laundering” and are prohibited under this Policy:</p>
                            <p className='paragraph'>
                              
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>a.</p>
                                        <p className='divalphabelt'>
                                            the transfer of funds to a Jupit account knowing or suspecting that such funds is derived from criminal or certain specified unlawful activity, for the purpose of disguising the illicit origin of the funds.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>b.</p>
                                        <p className='divalphabelt'>
                                            conducting any type of exchange transaction which involves criminally acquired funds;
                                        </p>	
                                </p>

                                <p className='specialParagraph'>
                                    <p className='alphabelt'>c.</p>
                                        <p className='divalphabelt'>
                                            the concealment or disguise of the true nature, source, disposition, transfer, rights with respect to ownership or control of criminal funds;
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>d.</p>
                                        <p className='divalphabelt'>
                                            promoting the carrying on of unlawful activity; and
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>e.</p>
                                        <p className='divalphabelt'>
                                            participation in, association to commit, attempts to commit and aiding, abetting, facilitating and counselling the commission of any of the actions mentioned in the foregoing points.
                                        </p>	
                                </p>
  
                            </p>
                        
                        </div>

                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>Red Flag</div>
                        <div className='policyText-content'>
                            <p>Where any suspicions arise that criminal conduct may have taken place involving a user, employee or third party, you should consider whether there is a risk that money laundering or terrorist financing has occurred or may occur.</p>
                            <p>Some examples of red flags to be reported include:</p>
                            <p className='paragraph'>
                              
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>a.</p>
                                        <p className='divalphabelt'>
                                            A user provides insufficient, false or suspicious information or is reluctant to provide complete information.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>b.</p>
                                        <p className='divalphabelt'>
                                        Methods or volumes of payment that are not consistent with the payment policy or that are not customarily used in the course of business, e.g., cash deposit by third party, payments with cheques, and/or payment transfer from unrelated third parties.
                                        </p>	
                                </p>

                                <p className='specialParagraph'>
                                    <p className='alphabelt'>c.</p>
                                        <p className='divalphabelt'>
                                        Structuring transactions to avoid government reporting or record keeping requirements.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>d.</p>
                                        <p className='divalphabelt'>
                                        Wire transfer activity that is not consistent with the activities of the customer, or which originates or terminates with parties unrelated to the transaction.
                                        </p>	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>e.</p>
                                        <p className='divalphabelt'>
                                        Unexpected spikes in a customer’s activities.
                                        </p>	
                                </p>
 
                            </p>
                            
                        </div>

                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>What's the Risk ?</div>
                        <div className='policyText-content'>
                            <p>Violating the Anti-money laundry laws may lead to severe civil and criminal penalties. These could include hefty fines, imprisonment, extradition, blacklisting, and the revocation business operation. In addition, violations of AML laws can have substantial consequences, such as damage to reputation and commercial relationships, restrictions in the way we can business, and the enormous time and cost of conducting internal investigations and/or defenses against government investigations and enforcement actions.</p>
                            
                        </div>

                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>Compliance Controls</div>
                        <div className='policyText-content'>
                            <p>Jupit is responsible for ensuring that its business has a culture of compliance and effective controls to comply with AML laws and regulations to prevent, detect and respond to money laundering and counter-terrorism financing and to communicate the serious consequences of non-compliance to employees and users.</p>
                            
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Know Your Customer (KYC) Procedures</div>
                        <div className='policyText-content'>
                            <p>Jupit Technologies is strongly committed to complying with all the applicable anti-money laundering rules within the regulatory framework and in order to adhere to these regulatory standards and to aid in prevention of money laundry or terrorist financing, Jupit will implement processes and procedures in its Line of Businesses (LOBs) to conduct appropriate customer due diligence ("DD") on the basis of the following “Know Your Customer” principles: ·</p>
                            <p className='paragraph'>
                              
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>.</p>
                                        <p className='divalphabelt'>
                                            <span className='alphabelt'>Customer Personal Details (Account Opening);</span>
                                           
                                        </p>
                               	
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>.</p>
                                    <p className='divalphabelt'>
                                            
                                            <span className='alphabelt'>Bank Verification Number (Verification Checking);</span>
                                            
                                        </p>
                                </p>
                                <p className='specialParagraph'>
                                    <p className='alphabelt'>.</p>
                                    <p className='divalphabelt'>
                                            
                                        <span className='alphabelt'>Valid Government Issued Identity Card and Selfie (Ownership Verification).</span>
                                            
                                        </p>
                                </p>
                            </p>
                            <p>
                                As an extra measure to the procedure, Jupit may perform enhanced due diligence procedures for customers presenting a higher risk, such as those transacting large volumes frequently etc. Unusual activity during the customer due diligence process or customer engagement should be reported immediately to the designated Jupit Compliance department or Commercial department.
                            </p>
                           
                        </div>


                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>Applicable Regulatory Framework</div>
                        <div className='policyText-content'>
                            <p>Jupit complies with all applicable AML/CTF laws and regulations, Financial Action Task Force (FATF) Recommendations and additional local AML regulations as required.</p>
                            
                        </div>

                    </div>

                    <div className='policyText'>
                        <div className='policyText-Title'>Non-compliance</div>
                        <div className='policyText-content'>
                            <p>Any Jupit employee or customer, who violates this Policy may be subject to appropriate disciplinary action, independently from potential other penalties resulting from their behavior.</p>
                            <p>Internal Audit shall conduct regular checks on business operations to ensure compliance with AML Laws.</p>
                        </div>

                    </div>
                    <div className='policyText'>
                        <div className='policyText-Title'>Updates, Review and Ownership</div>
                        <div className='policyText-content'>
                            <p>This Policy may be updated from time, and the updated version of the Policy will be immediately made available on the Jupit website.</p>
                            
                        </div>

                    </div>
             </div>
          
        </div>
    )
}
export default Index;